//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookshopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class authors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public authors()
        {
            this.archive_books = new HashSet<archive_books>();
            this.books = new HashSet<books>();
        }
    
        public int id { get; set; }
        public Nullable<int> last_name_id { get; set; }
        public int first_name_id { get; set; }
        public Nullable<int> middle_name_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archive_books> archive_books { get; set; }
        public virtual first_names first_names { get; set; }
        public virtual last_names last_names { get; set; }
        public virtual middle_names middle_names { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<books> books { get; set; }
    }
}
