//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookshopApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookshopEntities : DbContext
    {
        public BookshopEntities()
            : base("name=BookshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<archive_books> archive_books { get; set; }
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<first_names> first_names { get; set; }
        public virtual DbSet<genres> genres { get; set; }
        public virtual DbSet<last_names> last_names { get; set; }
        public virtual DbSet<middle_names> middle_names { get; set; }
        public virtual DbSet<publishers> publishers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
