//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookshopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int id { get; set; }
        public string book_name { get; set; }
        public int author_id { get; set; }
        public int publisher_id { get; set; }
        public int genre_id { get; set; }
        public int quantity { get; set; }
        public int price { get; set; }
        public int cost { get; set; }
        public int discount_percent { get; set; }
        public byte[] image { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual genres genres { get; set; }
        public virtual publishers publishers { get; set; }
    }
}
