//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookshopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> last_name_id { get; set; }
        public int first_name_id { get; set; }
        public Nullable<int> middle_name_id { get; set; }
        public bool is_admin { get; set; }
    
        public virtual first_names first_names { get; set; }
        public virtual last_names last_names { get; set; }
        public virtual middle_names middle_names { get; set; }
    }
}
